name: Trigger auto deployment for test123

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test123-AutoDeployTrigger-da7ff5a1-22c9-4b43-8481-bd38edf44b33.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEST123_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST123_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST123_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TEST123_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST123_REGISTRY_PASSWORD }}
          containerAppName: test123
          resourceGroup: westus-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


