name: Trigger auto deployment for test-action

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-action-AutoDeployTrigger-f9f44bbe-dbb8-4780-8c4c-10ba6893c046.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTACTION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTACTION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTACTION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TESTACTION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTACTION_REGISTRY_PASSWORD }}
          containerAppName: test-action
          resourceGroup: westus-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


